### ISSUE TITLE
Can't add new icons

### ISSUE THREAD

**Issue by QNTLO** [AurelienLoyer/domoticz_custom_icon_generator#13]
I could only find older issues that were resolved by updates. 
I've added a couple of icons through your tool, but now my domoticz doesn't add anymore. 
When I remove a custom icon, I can't add it, so it is not an issue of being 'full'. 

Could you help, since I don't have a clue where to start.

**Comment by peteralm097** [comment]
This seems to have been fixed from build 15378 onwards
