### ISSUE TITLE
Website https://domoticz-icon.aurelien-loyer.fr/ offline??

### ISSUE THREAD

**Issue by waltervl** [AurelienLoyer/domoticz_custom_icon_generator#14]
The website https://domoticz-icon.aurelien-loyer.fr/ is off line.
Any chance it will be enabled soon?
See also discussion https://www.domoticz.com/forum/viewtopic.php?p=312505#p312505

**Comment by gizmocuz** [comment]
Created

https://www.domoticz.com/icon-creator/

**Comment by AurelienLoyer** [comment]
Site is back online ! Sorry for the host issue 😅

**Comment by waltervl** [comment]
Thanks!
