### ISSUE TITLE
Not functional anymore

### ISSUE THREAD

**Issue by wjmulder78** [AurelienLoyer/domoticz_custom_icon_generator#18]
Dear Aurelien,

Although I used your online icon generator frequently with succes, unfortunately I noticed that it does not download/compile a zip-file anymore when 'Generate ZIP' is pressed.

Hopefully you have time to fix this issue,

With regards,
WJ

**Comment by AurelienLoyer** [comment]
Hey @wjmulder78, i just did a fix, let me know if everything is working fine now.

Sorry for the issue!

**Comment by wjmulder78** [comment]
Dear Aurélien,

It works like before (great!!)
Thank you for the effort!

With regards,
Willem Jan

Op ma 29 apr 2024 om 22:06 schreef Aurélien Loyer ***@***.***
